name: Deploy to Prod

on:
  push:
    branches:
      - workspace_publish
  workflow_dispatch: 

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        ref: workspace_publish

    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Deploy Synapse
      uses: Azure/arm-deploy@v1
      with:
        resourceGroupName: rg_synapse_project
        subscriptionId: ${{ fromJson(secrets.AZURE_CREDENTIALS).subscriptionId }}
        template: ./TemplateForWorkspace.json
        parameters: @./TemplateParametersForWorkspace_prod.json
